apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://192.168.58.2:30033/balmburren_db?serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=root
    spring.datasource.password=secret
    security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    security.jwt.expiration-time=86400000
    server.port=8006
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver