version: '3'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
#      - ./init:/docker-entrypoint-initdb.d
#    labels:
#      org.springframework.boot.service-connection: mysql
    networks:
      - network


  backend:
    build:
      context: .
      dockerfile: Dockerfile
#    env_file: ./.env
    ports:
      - 8005:8080
    #network_mode: "host"
#    expose:
#      - 8082
#    environment:
#      - DATABASE_HOST=mysqldb
#        - DATABASE_USER=root
#        - DATABASE_PASSWORD=secret
#        - DATABASE_NAME=balmburren_db
#        - DATABASE_PORT=3307
#        - spring.datasource.username=root
#        - spring.datasource.password=secret
#        - spring.datasource.url=jdbc:mysql://mysqldb:3307/balmburren_db?allowPublicKeyRetrieval=true&useSSL=false

#    environment:
#      SPRING_APPLICATION_JSON: '{
#              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/balmburren_db,
#              "spring.datasource.username" : "$MYSQLDB_USER",
#              "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#
#              "spring.jpa.hibernate.ddl-auto" : "update",
#              "spring.jpa.open-in-view"  :  "false",
#              "security.jwt.secret-key"  :  "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b",
#              "security.jwt.expiration-time"  :  "86400000",
#              "spring.datasource.driver-class-name"  :  "com.mysql.cj.jdbc.Driver"
#            }'
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/balmburren_db?allowPublicKeyRetrieval=true&useSSL=false
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
    networks:
      - network
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3307

#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3307/balmburren_db?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysqldb


#    volumes:
#        - .m2:/root/.m2


  frontend:
    build:
      context: ./frontend/src/main/angularclient
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - network


volumes:
  dbdata:
networks:
  network:
    driver: bridge





