version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$MYSQLDB_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # You may adjust this based on your DB initialization time



  backend:
    image: baernu/balmburren_backend:v1.0.0
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
#    env_file: ./.env
    ports:
      - 8081:8080

    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3307


#    depends_on:
#      - mysqldb

    depends_on:
      mysqldb:
        condition: service_healthy  # Ensures backend waits for MySQL to be healthy




  frontend:
    image: baernu/balmburren_frontend:v1.0.0
    build:
      context: ./frontend/src/main/angularclient
      dockerfile: Dockerfile
    ports:
      - 4200:80



volumes:
  dbdata:






