apiVersion: batch/v1
kind: CronJob
metadata:
  name: exoscale-to-scaleway-sync
  namespace: default
spec:
  schedule: "0 4 * * *"  # Runs daily at 4 AM, 2 hours after the backup
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rclone
              image: rclone/rclone:latest
              volumeMounts:
                - name: rclone-config
                  mountPath: /config/rclone
                  subPath: rclone.conf
              command: ["/bin/sh", "-c"]
              args:
                - |
                  rclone sync exoscale:your-exoscale-bucket scaleway:balmburren-bucket \
                  --config /config/rclone/rclone.conf --progress
          restartPolicy: OnFailure
          volumes:
            - name: rclone-config
              configMap:
                name: rclone-config