apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: mysql-restore-scaleway
  namespace: default
spec:
  backend:
    repoPasswordSecretRef:
      name: s3-backup-credentials  # Secret containing the Restic password
      key: repoPassword
    s3:
      endpoint: https://s3.fr-par.scw.cloud
      bucket: balmburren-bucket  # Replace with your actual Scaleway bucket name
      accessKeyIDSecretRef:
        name: scaleway-credentials
        key: accessKeyId
      secretAccessKeySecretRef:
        name: scaleway-credentials
        key: secretAccessKey
  snapshot: latest  # This restores the most recent snapshot.
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5