apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: mysql-backup-scaleway
  namespace: default
spec:
  backend:
    repoPasswordSecretRef:
      name: s3-backup-credentials  # Secret containing the Restic password
      key: repoPassword
    s3:
      endpoint: https://s3.fr-par.scw.cloud  # Scaleway S3-compatible endpoint
      bucket: balmburren-bucket  # Replace with your actual Scaleway bucket name
      accessKeyIDSecretRef:
        name: scaleway-credentials
        key: accessKeyId
      secretAccessKeySecretRef:
        name: scaleway-credentials
        key: secretAccessKey
  failedJobsHistoryLimit: 5  # Keep records of the last 5 failed jobs
  successfulJobsHistoryLimit: 14  # Keep records of the last 14 successful jobs

