apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: mysql-restore-scaleway
  namespace: default
spec:
  backend:
    s3:
      endpoint: https://balmburren-bucket.s3.fr-par.scw.cloud  # Scaleway S3-compatible endpoint
      bucket: balmburren-bucket           # Replace with your Scaleway bucket name
      accessKeyIDSecretRef:
        name: scaleway-credentials
        key: accessKeyId
      secretAccessKeySecretRef:
        name: scaleway-credentials
        key: secretAccessKey
    repoPasswordSecretRef:
      name: backup-repo
      key: password
  snapshot: "path/to/your-backup/db-backup-2024-10-22.sql.gz"  # Specify the exact backup file path
  keepJobs: 5  # Optional: Keeps the last 5 restore job records for analysis