apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore-from-pvc
  namespace: balmburren
spec:
  template:
    spec:
      containers:
        - name: mysql-restore
          image: mysql:8
          command:
            - sh
            - -c
            - |
              echo "Starting MySQL restore..."
              if [ -f "/mnt/restore/data/backup.sql" ]; then
                mysql -h mysqldb -u root -psecret --port=3307 balmburren_db< /mnt/restore/data/backup.sql
              else
                echo "backup.sql not found in /mnt/restore/data"
                exit 1
              fi
              echo "Restore completed successfully."
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQLDB_ROOT_PASSWORD
          volumeMounts:
            - name: restore-storage
              mountPath: /mnt/restore
      volumes:
        - name: restore-storage
          persistentVolumeClaim:
            claimName: mysql-restore-pvc
      restartPolicy: OnFailure
  backoffLimit: 4