apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-dump-backup
  namespace: balmburren
spec:
  schedule: "0 */3 * * *"  # Run every 3 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysqldump
              image: mysql:8
              command:
                - sh
                - -c
                - |
                  rm -rf /data/* && \
                  mkdir -p /data && \
                  mysqldump -u root -psecret -h mysqldb --port=3307 balmburren_db > /data/backup.sql 2> /data/backup_error.log
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-env-secret
                      key: MYSQLDB_ROOT_PASSWORD
              volumeMounts:
                - name: backup-storage
                  mountPath: /data

            - name: restic-backup
              image: restic/restic
              command:
                - sh
                - -c
                - |
                  restic -r s3:https://s3.fr-par.scw.cloud/balmburren-bucket backup /data \
                    --exclude='/data/mysql-restore-pvc' \
                    --exclude='/balmburren-mysqldump' \
                    --exclude='/data/mysql-pv-claim'
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: scaleway-credentials
                      key: accessKeyId
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: scaleway-credentials
                      key: secretAccessKey
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: repoPassword
              volumeMounts:
                - name: backup-storage
                  mountPath: /data

          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backup-pvc