apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
  namespace: balmburren
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
        - env:
#            - name: MYSQL_DATABASE
#              valueFrom:
#                configMapKeyRef:
#                  key: MYSQLDB_DATABASE
#                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQLDB_ROOT_PASSWORD
                  name: env
#            - name: MYSQLDB_USER
#              valueFrom:
#                configMapKeyRef:
#                  key: MYSQLDB_USER
#                  name: env
          image: mysql:8.0
          name: mysqldb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
#            - mountPath: "/var/lib/mysql"
#              subPath: "mysql" #added
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-persistent-storage
          persistentVolumeClaim:
              claimName: mysql-pv-claim
