apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: mysql-backup-exoscale
  namespace: default
spec:
  backend:
    s3:
      accessKeyIDSecretRef:
        name: exoscale-credentials
        key: EXOd5d233c3a68b6dbea981035d
      secretAccessKeySecretRef:
        name: exoscale-credentials
        key: vHsHqZfQmKIlNwUqOb0Amydkhp1UYiTbI7URkc-Mm-I
      bucket: your-exoscale-bucket
#      region: ch-dk-2  # Replace with your Exoscale region
      endpoint: https://sos-ch-dk-2.exo.io
#  schedule: "0 2 * * *"  # Runs daily at 2 AM
#  retention:
#    keepLast: 7  # Keep the last 7 backups
#  fileFormat: tgz
#  preBackup:
#    pod:
#      spec:
#        containers:
#          - name: mysql-dump
#            image: mysql:8
#            env:
#              - name: MYSQL_USER
#                valueFrom:
#                  secretKeyRef:
#                    name: mysql-env-secret
#                    key: MYSQLDB_USER
#              - name: MYSQL_PASSWORD
#                valueFrom:
#                  secretKeyRef:
#                    name: mysql-env-secret
#                    key: MYSQLDB_ROOT_PASSWORD
#              - name: MYSQL_DATABASE
#                valueFrom:
#                  secretKeyRef:
#                    name: mysql-env-secret
#                    key: MYSQLDB_DATABASE
#            command: ["/bin/sh", "-c"]
#            args:
#              - |
#                mysqldump -h mysql-service -u $MYSQL_USER -p$MYSQL_PASSWORD --all-databases > /backup/db-backup.sql
#            volumeMounts:
#              - name: backup-storage
#                mountPath: /backup
#        restartPolicy: OnFailure
#        volumes:
#          - name: backup-storage
#            emptyDir: {}