apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: mysql-schedule-scaleway
  namespace: balmburren
spec:
  backend:
    repoPasswordSecretRef:
      name: s3-backup-credentials  # Secret containing the Restic password
      key: repoPassword
    s3:
      endpoint: https://s3.fr-par.scw.cloud  # Scaleway S3-compatible endpoint
      bucket: balmburren-bucket  # Replace with your actual Scaleway bucket name
      accessKeyIDSecretRef:
        name: scaleway-credentials
        key: accessKeyId
      secretAccessKeySecretRef:
        name: scaleway-credentials
        key: secretAccessKey
  backup:
    schedule: '0 */3 * * *'  # Run every 3 hours
#    schedule: '*/2 * * * *'  # Run every 2 minutes for testing purposes
    failedJobsHistoryLimit: 2 # Keep records of the last 5 failed jobs
    successfulJobsHistoryLimit: 2  # Keep records of the last 14 successful jobs
  check:
    schedule: '*/30 * * * *'  # Run a check every 5 minutes
  prune:
    schedule: '*/30 * * * *'  # Prune old backups every 10 minutes
    retention:
      keepLast: 5
      keepDaily: 14
      keepMonthly: 12          # Retain one backup for each month, up to 12 months

