apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-restore-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust the storage size as needed
  storageClassName: manual
