apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: k8up-mysqldump
  namespace: balmburren
spec:
  backupCommand: sh -c "rm -rf /data/*  &&  mysqldump -u root -psecret -h mysqldb --port=3307 balmburren_db > /data/backup.sql 2> /data/backup_error.log"
  pod:
    spec:
      containers:
        - name: mysqldump
          image: mysql:8  # Use the MySQL image version that matches your database version

          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQLDB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQLDB_ROOT_PASSWORD
            - name: MYSQL_HOST
              value: mysqldb  # Replace with the actual service name of your MySQL instance
#            - name: MYSQL_DATABASE
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-env-secret
#                  key: MYSQLDB_DATABASE
          command:
            - sleep
            - infinity
          volumeMounts:
            - name: backup-storage
              mountPath: /data
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: mysql-backup-pvc  # PVC to store the backup file

