apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv
  namespace: balmburren
spec:
  capacity:
    storage: 200Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Match this to the PVC if needed
  hostPath:
    path: /mnt/data/mysql-backup  # Replace with a valid path on the node