apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-restore-pv
  namespace: balmburren
spec:
  capacity:
    storage: 50Gi  # Adjust the size based on your backup size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Match this with the PVC if needed
  hostPath:
    path: /mnt/data/mysql-restore  # Replace with a valid path on the node