apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
#  type: LoadBalancer #added
#  ports:
#    - name: "3307"
#  type: NodePort
  ports:
#    - nodePort: 30033
    - name: "pod-mysql"
      port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    io.kompose.service: mysqldb
