apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080  # Example NodePort (you can specify any available port in the range 30000-32767)
  selector:
    io.kompose.service: nginx-ingress