apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-backup-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust size as needed for the database dump