apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |
    [exoscale]
    type = s3
    provider = Ceph
    access_key_id = EXOd5d233c3a68b6dbea981035d
    secret_access_key = vHsHqZfQmKIlNwUqOb0Amydkhp1UYiTbI7URkc-Mm-I
    endpoint = https://sos-ch-dk-2.exo.io

    [scaleway]
    type = s3
    provider = Scaleway
    access_key_id = SCWWY1PJ5KT70EAQVX5D
    secret_access_key = 9ef51130-124e-43a4-8dbb-ce96ac11c947
    endpoint = s3.fr-par.scw.cloud