apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-check
  namespace: balmburren
spec:
  schedule: "0 4 * * *"  # Run daily at 4 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restic-check
              image: restic/restic
              command:
                - sh
                - -c
                - |
                  restic -r s3:https://s3.fr-par.scw.cloud/balmburren-bucket check
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: scaleway-credentials
                      key: accessKeyId
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: scaleway-credentials
                      key: secretAccessKey
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: repoPassword
          restartPolicy: OnFailure