apiVersion: v1
kind: Secret
metadata:
  name: scaleway-credentials
  namespace: balmburren
type: Opaque
data:
  accessKeyId: U0NXRzhHNjNSTkZaV0gyUlZUUTk=
  secretAccessKey: Y2UzZmY0ZmUtZTg0My00NjgxLTk4ZmQtNTdiYWFiOWMzY2Zk
