apiVersion: v1
kind: Service
metadata:
  name: tomcatappsvc
  namespace: tomcat-ps
spec:
  type: NodePort
  selector:
    app: tomcatapp
  ports:
    - port: 8006
      targetPort: 8080
      nodePort: 30006