apiVersion: v1
kind: Pod
metadata:
  name: tomcatapp
  namespace: tomcat-ps
  labels:
    app: tomcatapp
spec:
  containers:
    - name: tomcat
      image: tomcat:latest  # image
      ports:
        - containerPort: 8080